/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The audio_router marshal type definitions. This file is generated by D:/Work/Qcc/qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1/adk/tools/packages/typegen/typegen.py.
*/

#include <csrtypes.h>
#include <marshal_common.h>
#include <task_list.h>
#include <audio_router.h>
#include <app/marshal/marshal_if.h>
#include <audio_router_typedef.h>
#include <audio_router_marshal_typedef.h>

#include "domain_marshal_types.h"

const marshal_type_descriptor_t marshal_type_descriptor_audio_router_data_container_t = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(audio_router_data_container_t);


