/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The av c type definitions. This file is generated by D:/Work/Qcc/qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _AV_TYPEDEF_H__
#define _AV_TYPEDEF_H__

#include <csrtypes.h>
#include <marshal_common.h>
#include <task_list.h>

#include "avrcp_typedef.h"
#include "a2dp_typedef.h"
#include "av_callback_interface.h"

/*! AV Instance task data structure */
typedef struct 
{
    /*! Task/Message information for this instance */
    TaskData av_task;
    /*! Bluetooth Address of remote device */
    bdaddr bd_addr;
    /*! Delay timer for sending internal AVRCP pause for unrouted source post handover */
    uint8 send_avrcp_unrouted_pause_post_handover;
    /*! AVRCP task data */
    avrcpTaskData avrcp;
    /*! A2DP task data */
    a2dpTaskData a2dp;
    /*! Is a rejected connection expected */
    uint8 avrcp_reject_pending;
    /*! Flag indicating if the instance is about to be detatched */
    uint8 detach_pending;
    /*! A pointer to the plugin interface */
    const av_callback_interface_t *av_callbacks;
} avInstanceTaskData;

#endif /* _AV_TYPEDEF_H__ */

