/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_input_wired_analog_stereo.h
    \brief The chain_input_wired_analog_stereo chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_INPUT_WIRED_ANALOG_STEREO_H__
#define _CHAIN_INPUT_WIRED_ANALOG_STEREO_H__

/*!
\page chain_input_wired_analog_stereo
    @startuml
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_TTP_PASS
        object EPR_WIRED_STEREO_INPUT_L #lightgreen
        OPR_LATENCY_BUFFER "IN_L(0)" <-- EPR_WIRED_STEREO_INPUT_L
        object EPR_WIRED_STEREO_INPUT_R #lightgreen
        OPR_LATENCY_BUFFER "IN_R(1)" <-- EPR_WIRED_STEREO_INPUT_R
        object EPR_SOURCE_DECODED_PCM #lightblue
        EPR_SOURCE_DECODED_PCM <-- "OUT_L(0)" OPR_LATENCY_BUFFER
        object EPR_SOURCE_DECODED_PCM_RIGHT #lightblue
        EPR_SOURCE_DECODED_PCM_RIGHT <-- "OUT_R(1)" OPR_LATENCY_BUFFER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_input_wired_analog_stereo_config;

#endif /* _CHAIN_INPUT_WIRED_ANALOG_STEREO_H__ */

