/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_usb_voice_rx_stereo.c
    \brief The chain_usb_voice_rx_stereo chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#include <chain_usb_voice_rx_stereo.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../headset_cap_ids.h>
#include <kymera_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG_PRIORITY_MEDIUM(CAP_ID_USB_AUDIO_RX, OPR_USB_AUDIO_RX),
    MAKE_OPERATOR_CONFIG(CAP_ID_MIXER, OPR_LEFT_RIGHT_MIXER),
    MAKE_OPERATOR_CONFIG(CAP_ID_IIR_RESAMPLER, OPR_SPEAKER_RESAMPLER),
} ;

static const operator_endpoint_t inputs[] =
{
    {OPR_USB_AUDIO_RX, EPR_USB_FROM_HOST, 0},
} ;

static const operator_endpoint_t outputs[] =
{
    {OPR_SPEAKER_RESAMPLER, EPR_USB_RX_RESAMPLER_OUT, 0},
} ;

static const operator_connection_t connections[] =
{
    {OPR_USB_AUDIO_RX, 0, OPR_LEFT_RIGHT_MIXER, 0, 1},
    {OPR_USB_AUDIO_RX, 1, OPR_LEFT_RIGHT_MIXER, 1, 1},
    {OPR_LEFT_RIGHT_MIXER, 0, OPR_SPEAKER_RESAMPLER, 0, 1},
} ;

const chain_config_t chain_usb_voice_rx_stereo_config = {0, 0, operators, 3, inputs, 1, outputs, 1, connections, 3};

