/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_anc.c
    \brief The chain_anc chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#include <chain_anc.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../headset_cap_ids.h>
#include <kymera_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG(HS_CAP_ID_SWITCHED_PASSTHROUGH, OPR_ANC_SPC_1),
} ;

static const operator_endpoint_t inputs[] =
{
    {OPR_ANC_SPC_1, EPR_ANC_SPC_1_IN, 0},
    {OPR_ANC_SPC_1, EPR_ANC_SPC_2_IN, 1},
    {OPR_ANC_SPC_1, EPR_ANC_SPC_3_IN, 2},
    {OPR_ANC_SPC_1, EPR_ANC_SPC_4_IN, 3},
} ;

const chain_config_t chain_anc_config = {1, 0, operators, 1, inputs, 4, NULL, 0, NULL, 0};

