/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_prompt_aac.h
    \brief The chain_prompt_aac chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_PROMPT_AAC_H__
#define _CHAIN_PROMPT_AAC_H__

/*!
\page chain_prompt_aac
    @startuml
        object OPR_TONE_PROMPT_ENCODED_BUFFER
        OPR_TONE_PROMPT_ENCODED_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_AAC_DECODER
        OPR_AAC_DECODER : id = CAP_ID_AAC_DECODER
        object OPR_TONE_PROMPT_DECODED_BUFFER
        OPR_TONE_PROMPT_DECODED_BUFFER : id = CAP_ID_BASIC_PASS
        OPR_AAC_DECODER "IN(0)"<-- "OUT(0)" OPR_TONE_PROMPT_ENCODED_BUFFER
        OPR_TONE_PROMPT_DECODED_BUFFER "IN(0)"<-- "OUT(0)" OPR_AAC_DECODER
        object EPR_PROMPT_IN #lightgreen
        OPR_TONE_PROMPT_ENCODED_BUFFER "IN(0)" <-- EPR_PROMPT_IN
        object EPR_TONE_PROMPT_CHAIN_OUT #lightblue
        EPR_TONE_PROMPT_CHAIN_OUT <-- "OUT(0)" OPR_TONE_PROMPT_DECODED_BUFFER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_prompt_aac_config_p0;

extern const chain_config_t chain_prompt_aac_config_p1;

#endif /* _CHAIN_PROMPT_AAC_H__ */

