/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_output_volume_stereo.h
    \brief The chain_output_volume_stereo chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_OUTPUT_VOLUME_STEREO_H__
#define _CHAIN_OUTPUT_VOLUME_STEREO_H__

/*!
\page chain_output_volume_stereo
    @startuml
        object OPR_SOURCE_SYNC
        OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
        object OPR_VOLUME_CONTROL
        OPR_VOLUME_CONTROL : id = CAP_ID_OUTPUT_VOL_CTRL
        OPR_VOLUME_CONTROL "MAIN_IN_L(0)"<-- "OUT_L(0)" OPR_SOURCE_SYNC
        OPR_VOLUME_CONTROL "MAIN_IN_R(2)"<-- "OUT_R(1)" OPR_SOURCE_SYNC
        object EPR_SINK_STEREO_MIXER_L #lightgreen
        OPR_SOURCE_SYNC "IN_L(0)" <-- EPR_SINK_STEREO_MIXER_L
        object EPR_SINK_STEREO_MIXER_R #lightgreen
        OPR_SOURCE_SYNC "IN_R(1)" <-- EPR_SINK_STEREO_MIXER_R
        object EPR_VOLUME_AUX #lightgreen
        OPR_VOLUME_CONTROL "AUX_IN(1)" <-- EPR_VOLUME_AUX
        object EPR_SOURCE_STEREO_OUTPUT_L #lightblue
        EPR_SOURCE_STEREO_OUTPUT_L <-- "OUT_L(0)" OPR_VOLUME_CONTROL
        object EPR_SOURCE_STEREO_OUTPUT_R #lightblue
        EPR_SOURCE_STEREO_OUTPUT_R <-- "OUT_R(1)" OPR_VOLUME_CONTROL
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_output_volume_stereo_config;

#endif /* _CHAIN_OUTPUT_VOLUME_STEREO_H__ */

