/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_usb_voice_rx_mono.h
    \brief The chain_usb_voice_rx_mono chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_USB_VOICE_RX_MONO_H__
#define _CHAIN_USB_VOICE_RX_MONO_H__

/*!
\page chain_usb_voice_rx_mono
    @startuml
        object OPR_USB_AUDIO_RX
        OPR_USB_AUDIO_RX : id = CAP_ID_USB_AUDIO_RX
        object OPR_SPEAKER_RESAMPLER
        OPR_SPEAKER_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        OPR_SPEAKER_RESAMPLER "IN(0)"<-- "OUT(0)" OPR_USB_AUDIO_RX
        object EPR_USB_FROM_HOST #lightgreen
        OPR_USB_AUDIO_RX "USB_IN(0)" <-- EPR_USB_FROM_HOST
        object EPR_USB_RX_RESAMPLER_OUT #lightblue
        EPR_USB_RX_RESAMPLER_OUT <-- "OUT(0)" OPR_SPEAKER_RESAMPLER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_usb_voice_rx_mono_config;

#endif /* _CHAIN_USB_VOICE_RX_MONO_H__ */

