/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_input_aac_stereo.h
    \brief The chain_input_aac_stereo chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_INPUT_AAC_STEREO_H__
#define _CHAIN_INPUT_AAC_STEREO_H__

/*!
\page chain_input_aac_stereo
    @startuml
        object OPR_RTP_DECODER
        OPR_RTP_DECODER : id = CAP_ID_RTP_DECODE
        object OPR_AAC_DECODER
        OPR_AAC_DECODER : id = HS_CAP_ID_AAC_DECODER
        OPR_AAC_DECODER "IN(0)"<-- "OUT(0)" OPR_RTP_DECODER
        object EPR_SINK_MEDIA #lightgreen
        OPR_RTP_DECODER "IN(0)" <-- EPR_SINK_MEDIA
        object EPR_SOURCE_DECODED_PCM #lightblue
        EPR_SOURCE_DECODED_PCM <-- "OUT_L(0)" OPR_AAC_DECODER
        object EPR_SOURCE_DECODED_PCM_RIGHT #lightblue
        EPR_SOURCE_DECODED_PCM_RIGHT <-- "OUT_R(1)" OPR_AAC_DECODER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_input_aac_stereo_config_p0;

extern const chain_config_t chain_input_aac_stereo_config_p1;

#endif /* _CHAIN_INPUT_AAC_STEREO_H__ */

