/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_mic_resampler.h
    \brief The chain_mic_resampler chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_MIC_RESAMPLER_H__
#define _CHAIN_MIC_RESAMPLER_H__

/*!
\page chain_mic_resampler
    @startuml
        object OPR_MIC_RESAMPLER
        OPR_MIC_RESAMPLER : id = CAP_ID_IIR_RESAMPLER
        object EPR_AEC_RESAMPLER_IN_REF #lightgreen
        OPR_MIC_RESAMPLER "IN_REF(0)" <-- EPR_AEC_RESAMPLER_IN_REF
        object EPR_MIC_RESAMPLER_IN1 #lightgreen
        OPR_MIC_RESAMPLER "IN1(1)" <-- EPR_MIC_RESAMPLER_IN1
        object EPR_MIC_RESAMPLER_IN2 #lightgreen
        OPR_MIC_RESAMPLER "IN2(2)" <-- EPR_MIC_RESAMPLER_IN2
        object EPR_MIC_RESAMPLER_IN3 #lightgreen
        OPR_MIC_RESAMPLER "IN3(3)" <-- EPR_MIC_RESAMPLER_IN3
        object EPR_MIC_RESAMPLER_IN4 #lightgreen
        OPR_MIC_RESAMPLER "IN4(4)" <-- EPR_MIC_RESAMPLER_IN4
        object EPR_MIC_RESAMPLER_IN5 #lightgreen
        OPR_MIC_RESAMPLER "IN5(5)" <-- EPR_MIC_RESAMPLER_IN5
        object EPR_MIC_RESAMPLER_IN6 #lightgreen
        OPR_MIC_RESAMPLER "IN6(6)" <-- EPR_MIC_RESAMPLER_IN6
        object EPR_MIC_RESAMPLER_IN7 #lightgreen
        OPR_MIC_RESAMPLER "IN7(7)" <-- EPR_MIC_RESAMPLER_IN7
        object EPR_AEC_RESAMPLER_OUT_REF #lightblue
        EPR_AEC_RESAMPLER_OUT_REF <-- "OUT_REF(0)" OPR_MIC_RESAMPLER
        object EPR_MIC_RESAMPLER_OUT1 #lightblue
        EPR_MIC_RESAMPLER_OUT1 <-- "OUT1(1)" OPR_MIC_RESAMPLER
        object EPR_MIC_RESAMPLER_OUT2 #lightblue
        EPR_MIC_RESAMPLER_OUT2 <-- "OUT2(2)" OPR_MIC_RESAMPLER
        object EPR_MIC_RESAMPLER_OUT3 #lightblue
        EPR_MIC_RESAMPLER_OUT3 <-- "OUT3(3)" OPR_MIC_RESAMPLER
        object EPR_MIC_RESAMPLER_OUT4 #lightblue
        EPR_MIC_RESAMPLER_OUT4 <-- "OUT4(4)" OPR_MIC_RESAMPLER
        object EPR_MIC_RESAMPLER_OUT5 #lightblue
        EPR_MIC_RESAMPLER_OUT5 <-- "OUT5(5)" OPR_MIC_RESAMPLER
        object EPR_MIC_RESAMPLER_OUT6 #lightblue
        EPR_MIC_RESAMPLER_OUT6 <-- "OUT6(6)" OPR_MIC_RESAMPLER
        object EPR_MIC_RESAMPLER_OUT7 #lightblue
        EPR_MIC_RESAMPLER_OUT7 <-- "OUT7(7)" OPR_MIC_RESAMPLER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_mic_resampler_config;

#endif /* _CHAIN_MIC_RESAMPLER_H__ */

