/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_music_processing_user_eq.h
    \brief The chain_music_processing_user_eq chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_MUSIC_PROCESSING_USER_EQ_H__
#define _CHAIN_MUSIC_PROCESSING_USER_EQ_H__

/*!
\page chain_music_processing_user_eq
    @startuml
        object OPR_ADD_HEADROOM
        OPR_ADD_HEADROOM : id = CAP_ID_BASIC_PASS
        object OPR_SPEAKER_EQ
        OPR_SPEAKER_EQ : id = CAP_ID_PEQ
        object OPR_USER_EQ
        OPR_USER_EQ : id = CAP_ID_PEQ
        object OPR_REMOVE_HEADROOM
        OPR_REMOVE_HEADROOM : id = CAP_ID_BASIC_PASS
        OPR_SPEAKER_EQ "IN_L(0)"<-- "OUT_L(0)" OPR_ADD_HEADROOM
        OPR_SPEAKER_EQ "IN_R(1)"<-- "OUT_R(1)" OPR_ADD_HEADROOM
        OPR_USER_EQ "IN_L(0)"<-- "OUT_L(0)" OPR_SPEAKER_EQ
        OPR_USER_EQ "IN_R(1)"<-- "OUT_R(1)" OPR_SPEAKER_EQ
        OPR_REMOVE_HEADROOM "IN_L(0)"<-- "OUT_L(0)" OPR_USER_EQ
        OPR_REMOVE_HEADROOM "IN_R(1)"<-- "OUT_R(1)" OPR_USER_EQ
        object EPR_MUSIC_PROCESSING_IN_L #lightgreen
        OPR_ADD_HEADROOM "IN_L(0)" <-- EPR_MUSIC_PROCESSING_IN_L
        object EPR_MUSIC_PROCESSING_IN_R #lightgreen
        OPR_ADD_HEADROOM "IN_R(1)" <-- EPR_MUSIC_PROCESSING_IN_R
        object EPR_MUSIC_PROCESSING_OUT_L #lightblue
        EPR_MUSIC_PROCESSING_OUT_L <-- "OUT_L(0)" OPR_REMOVE_HEADROOM
        object EPR_MUSIC_PROCESSING_OUT_R #lightblue
        EPR_MUSIC_PROCESSING_OUT_R <-- "OUT_R(1)" OPR_REMOVE_HEADROOM
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_music_processing_user_eq_config_p0;

extern const chain_config_t chain_music_processing_user_eq_config_p1;

#endif /* _CHAIN_MUSIC_PROCESSING_USER_EQ_H__ */

