/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_anc.h
    \brief The chain_anc chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#ifndef _CHAIN_ANC_H__
#define _CHAIN_ANC_H__

/*!
\page chain_anc
    @startuml
        object OPR_ANC_SPC_1
        OPR_ANC_SPC_1 : id = HS_CAP_ID_SWITCHED_PASSTHROUGH
        object EPR_ANC_SPC_1_IN #lightgreen
        OPR_ANC_SPC_1 "IN_1(0)" <-- EPR_ANC_SPC_1_IN
        object EPR_ANC_SPC_2_IN #lightgreen
        OPR_ANC_SPC_1 "IN_2(1)" <-- EPR_ANC_SPC_2_IN
        object EPR_ANC_SPC_3_IN #lightgreen
        OPR_ANC_SPC_1 "IN_3(2)" <-- EPR_ANC_SPC_3_IN
        object EPR_ANC_SPC_4_IN #lightgreen
        OPR_ANC_SPC_1 "IN_4(3)" <-- EPR_ANC_SPC_4_IN
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_anc_config;

#endif /* _CHAIN_ANC_H__ */

