/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \file chain_output_volume_common.c
    \brief The chain_output_volume_common chain.

    This file is generated by D:\Work\Qcc\qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1\adk\tools\packages\chaingen\chaingen_mod\__init__.pyc.
*/

#include <chain_output_volume_common.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../headset_cap_ids.h>
#include <kymera_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG_PRIORITY_MEDIUM(CAP_ID_SOURCE_SYNC, OPR_SOURCE_SYNC),
    MAKE_OPERATOR_CONFIG_PRIORITY_MEDIUM(CAP_ID_OUTPUT_VOL_CTRL, OPR_VOLUME_CONTROL),
} ;

static const operator_endpoint_t inputs[] =
{
    {OPR_SOURCE_SYNC, EPR_SINK_STEREO_MIXER_L, 0},
    {OPR_SOURCE_SYNC, EPR_SINK_STEREO_MIXER_R, 1},
    {OPR_VOLUME_CONTROL, EPR_VOLUME_AUX, 1},
} ;

static const operator_endpoint_t outputs[] =
{
    {OPR_VOLUME_CONTROL, EPR_SOURCE_STEREO_OUTPUT_L, 0},
    {OPR_VOLUME_CONTROL, EPR_SOURCE_STEREO_OUTPUT_R, 1},
} ;

static const operator_connection_t connections[] =
{
    {OPR_SOURCE_SYNC, 0, OPR_VOLUME_CONTROL, 0, 1},
    {OPR_SOURCE_SYNC, 1, OPR_VOLUME_CONTROL, 2, 1},
} ;

const chain_config_t chain_output_volume_common_config = {0, 0, operators, 2, inputs, 3, outputs, 2, connections, 2};

