/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The hfp_profile_states marshal type definitions. This file is generated by D:/Work/Qcc/qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1/adk/tools/packages/typegen/typegen.py.
*/

#include <csrtypes.h>
#include <marshal_common.h>
#include <app/marshal/marshal_if.h>
#include <hfp_profile_states_typedef.h>
#include <hfp_profile_states_marshal_typedef.h>

const marshal_type_descriptor_t marshal_type_descriptor_hfpState = MAKE_MARSHAL_TYPE_DEFINITION_BASIC(hfpState);


