/*
    Warning - this file was autogenerated by genparse
    DO NOT EDIT - any changes will be lost
*/

#include "device_test_parse.h"

#include <ctype.h>
#include <panic.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <util.h> /* hash and compare */

#if defined(__KALIMBA__) && !defined(__GNUC__)
/* suppress warning caused for 'res' as compiler does not track into calls */
#pragma unitsuppress PossiblyUninitialized

/* Prototype of UtilHash differs on some versions of Kalimba libraries */
#define UTIL_HASH(_data,_size,_seed) UtilHash((const uint8*)(_data),_size,_seed)
#else
#define UTIL_HASH(_data,_size,_seed) UtilHash((const uint16*)(_data),_size,_seed)
#endif

typedef const uint8 *ptr;

static __inline__ char my_toupper(char c)
{ return (char)('a' <= c && c <= 'z' ? c +'A'-'a' : c); }

static const int hexdigit[] =
{
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,
    0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};

static ptr skip1(ptr s, ptr e)
{
  if(s)
    while(s != e && (*s == ' ' || *s == '\t'))
      ++s;
  return s;
}

static ptr match1(ptr s, ptr e)
{ return s && s != e && (*s == '\r' || *s == '\n') ? s+1 : 0; }

#ifdef TEST_HARNESS
static void printString(const char *name, const struct sequence *s)
{
  uint16 i;
  printf(" %s='", name);
  for(i = 0; i < s->length; ++i) putchar(s->data[i]);
  printf("'");
}
#endif

static __inline__ int isClass(char c, const int *a)
{
    return (c & ~0x7F) == 0 && a[(int)c];
}
 
static __inline__ ptr skipQuote(ptr p, ptr e)
{ return p && p != e && *p == '"' ? p+1 : p; }

static ptr getClassPlus(ptr p, ptr e, struct sequence *res, const int *a)
{
  p = skipQuote(p, e);
  if(p)
  {
    ptr s = p;
    while(p != e && isClass(*p, a)) ++p;
    if(p != s)
    {
        res->data = s;
        res->length = (uint16)(p - s);
			return skipQuote(p, e);
    }
    else
    {
        p = skipQuote(p, e);
        if (*p==',' || *p == '\r')
        {
            res->data = 0;
            res->length = 0;
            return 0;
        }
    }
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr skipOnce1(ptr s, ptr e)
{
  if(s)
  {
    if(s != e && (*s == ',' || *s == ';'))
      ++s;
  }
  return s;
}

static ptr getWildString(ptr p, ptr e, struct sequence *res)
{
  if(p)
  {
    ptr s = p;
    p = (uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16) (e - p));
    if (!p) p = (uint8*)UtilFind(0xFFFF, '\n', (const uint16*)p, 0, 1, (uint16) (e - p));
    if (!p) p = e;
    res->data = s;
    res->length = (uint16)(p - s);
    return p;
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr matchChar(ptr s, ptr e, uint8 c)
{ return s && s != e && my_toupper((char) *s) == (char) c ? s+1 : 0; }

static ptr findEndOfPacket(ptr s, ptr e)
{
  /*
     Returns
     0   if the buffer holds an incomplete packet
     s+1 if the buffer holds an invalid packet
     end of the first packet otherwise
  */
  if(s == e) return 0;

  if(*s == '\r')
  {
    /* expecting <cr> <lf> ... <cr> <lf> */
    if(e-s >= 4)
    {
      if(s[1] == '\n' && s[2] != '\r')
      {
        ptr p = s+2;
        if(*p != '\r')
        {
#ifndef TEST_HARNESS
        p = (const uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16)(e-p));
#endif
#ifdef TEST_HARNESS
		   while(p != e && *p != '\r') p++;
#endif
        return p == 0 || p + 1 == e ? 0 /* no terminator yet */
             : p[1] == '\n' ? p+2 /* valid */
             : s+1 ; /* invalid terminator */
         }
         else
             return s+1;
      }
      else
      {
        return s+1;
      }
    }
    else
    {
      /* Can't tell yet */
      return 0;
    }
  }
  else
  {
    /* expecting ... <cr> */
    ptr p = s;
    while(p != e && (*p == ' ' || *p == '\0' || *p == '\t')) ++p;
    if(p != e && (*p == '\r' || *p == '\n' )) return s+1;
    while(p != e && *p != '\r') ++p;
    return p == e ? 0 : p+1;
  }
}

#ifndef TEST_HARNESS
#if (defined __XAP__ || defined __KALIMBA__)
uint16 DeviceTestServiceParser_parseSource(Source rfcDataIn, Task task)
{
  ptr s = SourceMap(rfcDataIn);
  ptr e = s + SourceSize(rfcDataIn);
  ptr p = DeviceTestServiceParser_parseData(s, e, task);
  if(p != s)
  {
    SourceDrop(rfcDataIn, (uint16) (p - s));
    return 1;
  }
  else
  {
    return 0;
  }
}
#endif
#endif

typedef struct {
  char c;
  int16 to;
} Arc;

static const Arc arcs[] = {
  { '\t', 0 },
  { ' ', 0 },
  { 'A', 1 },
  { 'T', 2 },
  { '\t', 2 },
  { ' ', 2 },
  { '+', 3 },
  { '\t', 3 },
  { ' ', 3 },
  { 'A', 4 },
  { 'B', 5 },
  { 'D', 6 },
  { 'L', 7 },
  { 'P', 8 },
  { 'R', 9 },
  { 'T', 10 },
  { 'N', 11 },
  { 'U', 12 },
  { 'A', 13 },
  { 'E', 14 },
  { 'T', 15 },
  { 'O', 16 },
  { 'S', 17 },
  { 'F', 18 },
  { 'S', 19 },
  { 'E', 20 },
  { 'C', 21 },
  { 'D', 22 },
  { 'T', 23 },
  { 'T', 24 },
  { 'V', 25 },
  { 'S', 26 },
  { 'C', 27 },
  { 'O', 28 },
  { 'K', 29 },
  { 'T', 30 },
  { 'S', 31 },
  { 'M', 32 },
  { 'S', 33 },
  { 'D', 34 },
  { 'E', 35 },
  { 'G', 36 },
  { 'R', 37 },
  { 'S', 38 },
  { 'W', 39 },
  { 'I', 40 },
  { 'H', 41 },
  { 'T', 42 },
  { 'C', 43 },
  { 'E', 44 },
  { 'S', 45 },
  { 'T', 46 },
  { 'A', 47 },
  { 'P', 48 },
  { 'E', 49 },
  { 'E', 50 },
  { 'I', 51 },
  { 'P', 52 },
  { 'T', 53 },
  { 'I', 54 },
  { 'N', 55 },
  { 'E', 56 },
  { 'E', 57 },
  { 'E', 58 },
  { 'R', 59 },
  { 'O', 60 },
  { 'D', 61 },
  { 'R', 62 },
  { 'S', 63 },
  { 'E', 64 },
  { 'F', 65 },
  { 'N', 66 },
  { 'E', 67 },
  { 'E', 68 },
  { 'L', 69 },
  { 'B', 70 },
  { 'Y', 71 },
  { 'S', 72 },
  { 'R', 73 },
  { 'E', 74 },
  { 'A', 75 },
  { 'H', 76 },
  { 'L', 77 },
  { 'P', 78 },
  { 'T', 79 },
  { 'S', 80 },
  { 'A', 81 },
  { 'T', 82 },
  { 'A', 83 },
  { 'T', 84 },
  { 'I', 85 },
  { 'P', 86 },
  { 'I', 87 },
  { 'E', 88 },
  { 'T', 89 },
  { 'R', 90 },
  { 'G', 91 },
  { 'D', 92 },
  { 'T', 93 },
  { 'S', 94 },
  { 'B', 95 },
  { 'A', 96 },
  { 'C', 97 },
  { 'G', 98 },
  { 'M', 99 },
  { 'S', 100 },
  { 'T', 101 },
  { 'E', 102 },
  { 'R', 103 },
  { 'C', 104 },
  { 'A', 105 },
  { 'E', 106 },
  { 'I', 107 },
  { 'R', 108 },
  { 'O', 109 },
  { 'A', 110 },
  { 'B', 111 },
  { 'P', 112 },
  { 'D', 113 },
  { 'F', 114 },
  { 'P', 115 },
  { 'T', 116 },
  { 'L', 117 },
  { 'S', 118 },
  { 'S', 119 },
  { 'A', 120 },
  { 'Y', 121 },
  { 'R', 122 },
  { 'U', 123 },
  { 'T', 124 },
  { 'T', 125 },
  { 'T', 126 },
  { 'D', 127 },
  { 'C', 128 },
  { 'L', 129 },
  { 'E', 130 },
  { 'I', 131 },
  { 'E', 132 },
  { 'C', 133 },
  { 'D', 134 },
  { 'L', 135 },
  { 'S', 136 },
  { 'T', 137 },
  { 'A', 138 },
  { 'A', 139 },
  { 'C', 140 },
  { 'L', 141 },
  { 'D', 142 },
  { 'O', 143 },
  { 'O', 144 },
  { 'U', 145 },
  { 'B', 146 },
  { 'L', 147 },
  { 'S', 148 },
  { 'C', 149 },
  { 'F', 150 },
  { 'I', 151 },
  { 'S', 152 },
  { 'E', 153 },
  { 'A', 154 },
  { 'A', 155 },
  { 'P', 156 },
  { 'R', 157 },
  { 'L', 158 },
  { 'E', 159 },
  { 'P', 160 },
  { 'E', 161 },
  { 'E', 162 },
  { 'M', 163 },
  { 'A', 164 },
  { 'K', 165 },
  { 'E', 166 },
  { 'T', 167 },
  { 'B', 168 },
  { 'T', 169 },
  { 'A', 170 },
  { 'F', 171 },
  { 'U', 172 },
  { 'E', 173 },
  { 'T', 174 },
  { 'X', 175 },
  { 'D', 176 },
  { 'T', 177 },
  { 'E', 178 },
  { 'L', 179 },
  { '\t', 142 },
  { ' ', 142 },
  { ':', -1 },
  { '=', -1 },
  { 'I', 180 },
  { 'O', 181 },
  { 'X', 182 },
  { 'C', 183 },
  { 'L', 184 },
  { 'E', 185 },
  { 'K', 186 },
  { 'O', 187 },
  { 'I', 188 },
  { 'N', 189 },
  { 'K', 190 },
  { 'F', 191 },
  { 'Y', 192 },
  { 'B', 193 },
  { '\t', 156 },
  { ' ', 156 },
  { ':', -2 },
  { '=', -2 },
  { 'T', 194 },
  { 'E', 195 },
  { 'A', 196 },
  { 'D', 197 },
  { 'S', 198 },
  { 'S', 199 },
  { 'O', 200 },
  { 'D', 201 },
  { 'S', 202 },
  { 'A', 203 },
  { '\t', 167 },
  { ' ', 167 },
  { ':', -3 },
  { '=', -3 },
  { 'G', 204 },
  { '\t', 169 },
  { ' ', 169 },
  { ':', -4 },
  { '=', -4 },
  { 'R', 205 },
  { 'G', 206 },
  { 'T', 207 },
  { 'R', 208 },
  { 'T', 209 },
  { 'O', 210 },
  { 'S', 211 },
  { '\t', 176 },
  { '\n', -5 },
  { '\r', -5 },
  { ' ', 176 },
  { 'U', 212 },
  { 'L', 213 },
  { 'E', 214 },
  { 'N', 215 },
  { 'U', 216 },
  { 'I', 217 },
  { 'H', 218 },
  { 'E', 219 },
  { '\t', 185 },
  { ' ', 185 },
  { ':', -6 },
  { '=', -6 },
  { 'E', 220 },
  { 'A', 221 },
  { 'N', 222 },
  { 'E', 223 },
  { 'E', 224 },
  { 'I', 225 },
  { 'T', 226 },
  { 'L', 227 },
  { '\t', 194 },
  { '\n', -7 },
  { '\r', -7 },
  { ' ', 194 },
  { 'V', 228 },
  { 'D', 229 },
  { '\t', 230 },
  { ' ', 230 },
  { ':', -8 },
  { '=', -8 },
  { 'P', 231 },
  { 'T', 232 },
  { 'T', 233 },
  { 'D', 234 },
  { 'D', 235 },
  { 'T', 236 },
  { 'R', 237 },
  { 'E', 238 },
  { 'R', 239 },
  { 'A', 240 },
  { 'C', 241 },
  { 'P', 242 },
  { 'S', 243 },
  { 'M', 244 },
  { 'X', 245 },
  { 'X', 246 },
  { 'P', 247 },
  { 'T', 248 },
  { 'R', 249 },
  { 'E', 250 },
  { 'F', 251 },
  { 'P', 252 },
  { 'T', 253 },
  { 'M', 254 },
  { '\t', 218 },
  { ' ', 218 },
  { ':', -9 },
  { '=', -9 },
  { '\t', 219 },
  { '\n', -10 },
  { '\r', -10 },
  { ' ', 219 },
  { 'Y', 255 },
  { 'R', 256 },
  { 'E', 257 },
  { 'G', 258 },
  { 'Y', 259 },
  { 'N', 260 },
  { 'E', 261 },
  { 'O', 262 },
  { 'E', 263 },
  { 'E', 264 },
  { '\t', 265 },
  { '\n', -11 },
  { '\r', -11 },
  { ' ', 265 },
  { '?', 266 },
  { 'P', 267 },
  { '\t', 230 },
  { ' ', 230 },
  { ':', -8 },
  { '=', -8 },
  { 'A', 268 },
  { 'I', 269 },
  { 'M', 270 },
  { 'E', 271 },
  { 'R', 272 },
  { 'A', 273 },
  { 'O', 274 },
  { '\t', 237 },
  { ' ', 237 },
  { ':', -12 },
  { '=', -12 },
  { 'T', 275 },
  { 'I', 276 },
  { 'D', 277 },
  { 'H', 278 },
  { 'A', 279 },
  { 'O', 280 },
  { 'T', 281 },
  { 'O', 282 },
  { 'S', 283 },
  { 'S', 284 },
  { '\t', 247 },
  { '\n', -13 },
  { '\r', -13 },
  { ' ', 247 },
  { 'A', 285 },
  { 'E', 286 },
  { 'R', 287 },
  { 'F', 288 },
  { 'U', 289 },
  { 'P', 290 },
  { 'I', 291 },
  { '\t', 255 },
  { ' ', 255 },
  { ':', 292 },
  { '=', 292 },
  { 'S', 293 },
  { 'G', 294 },
  { 'A', 295 },
  { '\t', 259 },
  { ' ', 259 },
  { ':', 296 },
  { '=', 296 },
  { 'E', 297 },
  { 'S', 298 },
  { 'N', 299 },
  { '\t', 263 },
  { '\n', -14 },
  { '\r', -14 },
  { ' ', 263 },
  { 'L', 300 },
  { '\t', 265 },
  { '\n', -11 },
  { '\r', -11 },
  { ' ', 265 },
  { '?', 266 },
  { '\t', 301 },
  { '\n', -11 },
  { '\r', -11 },
  { ' ', 301 },
  { '?', 266 },
  { 'A', 302 },
  { 'R', 303 },
  { 'N', 304 },
  { 'O', 305 },
  { '\t', 271 },
  { '\n', -15 },
  { '\r', -15 },
  { ' ', 271 },
  { '?', 306 },
  { '\t', 272 },
  { '\n', -16 },
  { '\r', -16 },
  { ' ', 272 },
  { '?', 307 },
  { 'R', 308 },
  { 'P', 309 },
  { '\t', 275 },
  { ' ', 275 },
  { ':', -17 },
  { '=', -17 },
  { 'E', 310 },
  { 'D', 311 },
  { 'A', 312 },
  { 'C', 313 },
  { 'W', 314 },
  { 'O', 315 },
  { 'D', 316 },
  { 'T', 317 },
  { 'T', 318 },
  { 'R', 319 },
  { '\t', 286 },
  { '\n', -18 },
  { '\r', -18 },
  { ' ', 286 },
  { '?', 320 },
  { 'O', 321 },
  { 'E', 322 },
  { 'T', 323 },
  { 'U', 324 },
  { 'T', 325 },
  { '\t', 292 },
  { ' ', 292 },
  { '0', 326 },
  { 'E', 327 },
  { 'A', 328 },
  { 'I', 329 },
  { '\t', 296 },
  { ' ', 296 },
  { '0', 330 },
  { 'G', 331 },
  { 'T', 332 },
  { 'E', 333 },
  { '\t', 300 },
  { '\n', -19 },
  { '\r', -19 },
  { ' ', 300 },
  { '?', 334 },
  { '\t', 301 },
  { '\n', -11 },
  { '\r', -11 },
  { ' ', 301 },
  { 'R', 335 },
  { 'T', 336 },
  { 'G', 337 },
  { 'D', 338 },
  { '\t', 339 },
  { '\n', -15 },
  { '\r', -15 },
  { ' ', 339 },
  { '?', 306 },
  { '\t', 340 },
  { '\n', -16 },
  { '\r', -16 },
  { ' ', 340 },
  { '?', 307 },
  { 'T', 341 },
  { '\t', 309 },
  { '\n', -20 },
  { '\r', -20 },
  { ' ', 309 },
  { 'R', 342 },
  { 'R', 343 },
  { 'N', 344 },
  { 'K', 345 },
  { 'E', 346 },
  { 'P', 347 },
  { 'E', 348 },
  { 'A', 349 },
  { 'A', 350 },
  { 'T', 351 },
  { '\t', 352 },
  { '\n', -18 },
  { '\r', -18 },
  { ' ', 352 },
  { '?', 320 },
  { 'M', 353 },
  { 'C', 354 },
  { 'P', 355 },
  { 'S', 356 },
  { 'T', 357 },
  { 'Y', 358 },
  { 'X', -21 },
  { 'G', 359 },
  { 'I', 360 },
  { 'N', 361 },
  { 'X', -22 },
  { 'A', 362 },
  { 'T', 363 },
  { '\t', 333 },
  { ' ', 333 },
  { ':', -23 },
  { '=', -23 },
  { '\t', 364 },
  { '\n', -19 },
  { '\r', -19 },
  { ' ', 364 },
  { '?', 334 },
  { 'T', 365 },
  { '\t', 336 },
  { ' ', 336 },
  { ':', -24 },
  { '=', -24 },
  { '\t', 337 },
  { ' ', 337 },
  { ':', -25 },
  { '=', -25 },
  { 'E', 366 },
  { '\t', 339 },
  { '\n', -15 },
  { '\r', -15 },
  { ' ', 339 },
  { '\t', 340 },
  { '\n', -16 },
  { '\r', -16 },
  { ' ', 340 },
  { '\t', 341 },
  { ' ', 341 },
  { ':', -26 },
  { '=', -26 },
  { '\t', 342 },
  { ' ', 342 },
  { ':', -27 },
  { '=', -27 },
  { 'E', 367 },
  { 'N', 368 },
  { 'E', 369 },
  { 'R', 370 },
  { 'P', 371 },
  { 'T', 372 },
  { '\t', 348 },
  { '\n', -28 },
  { '\r', -28 },
  { ' ', 348 },
  { 'R', 373 },
  { 'R', 374 },
  { '\t', 351 },
  { '\n', -29 },
  { '\r', -29 },
  { ' ', 351 },
  { '\t', 352 },
  { '\n', -18 },
  { '\r', -18 },
  { ' ', 352 },
  { 'E', 375 },
  { 'T', 376 },
  { 'I', 377 },
  { '\t', 356 },
  { '\n', -30 },
  { '\r', -30 },
  { ' ', 356 },
  { '\t', 357 },
  { ' ', 357 },
  { ':', -31 },
  { '=', -31 },
  { '\t', 358 },
  { ' ', 358 },
  { ':', -32 },
  { '=', -32 },
  { 'A', 378 },
  { 'N', 379 },
  { '\t', 380 },
  { ' ', 380 },
  { ':', -33 },
  { '=', -33 },
  { 'D', 381 },
  { 'I', 382 },
  { 'O', 383 },
  { '\t', 364 },
  { '\n', -19 },
  { '\r', -19 },
  { ' ', 364 },
  { '\t', 365 },
  { ' ', 365 },
  { ':', -34 },
  { '=', -34 },
  { '\t', 366 },
  { ' ', 366 },
  { ':', -35 },
  { '=', -35 },
  { 'S', 384 },
  { 'E', 385 },
  { 'T', 386 },
  { '\t', 370 },
  { ' ', 370 },
  { ':', -36 },
  { '=', -36 },
  { 'I', 387 },
  { 'I', 388 },
  { 'O', 389 },
  { 'T', 390 },
  { 'T', 391 },
  { 'T', 392 },
  { '\t', 376 },
  { ' ', 376 },
  { ':', -37 },
  { '=', -37 },
  { 'O', 393 },
  { 'I', 394 },
  { '\t', 395 },
  { ' ', 395 },
  { ':', -38 },
  { '=', -38 },
  { 'D', 396 },
  { '\t', 380 },
  { ' ', 380 },
  { ':', -33 },
  { '=', -33 },
  { 'U', 397 },
  { 'N', 398 },
  { 'N', 399 },
  { 'S', 400 },
  { 'L', 401 },
  { '\t', 386 },
  { ' ', 386 },
  { ':', 402 },
  { '=', 402 },
  { 'O', 403 },
  { 'M', 404 },
  { 'U', 405 },
  { '\t', 390 },
  { ' ', 390 },
  { ':', -39 },
  { '=', -39 },
  { '\t', 391 },
  { ' ', 391 },
  { ':', -40 },
  { '=', -40 },
  { 'E', 406 },
  { '\t', 393 },
  { ' ', 393 },
  { ':', -41 },
  { '=', -41 },
  { 'N', 407 },
  { '\t', 395 },
  { ' ', 395 },
  { ':', -38 },
  { '=', -38 },
  { 'U', 408 },
  { 'A', 409 },
  { '\t', 410 },
  { ' ', 410 },
  { ':', -42 },
  { '=', -42 },
  { 'D', 411 },
  { 'E', 412 },
  { '\t', 400 },
  { ' ', 400 },
  { ':', -43 },
  { '=', -43 },
  { '\t', 401 },
  { ' ', 401 },
  { ':', -44 },
  { '=', -44 },
  { '\t', 402 },
  { ' ', 402 },
  { '0', 413 },
  { '\t', 403 },
  { ' ', 403 },
  { ':', -45 },
  { '=', -45 },
  { 'E', 414 },
  { 'C', 415 },
  { 'R', 416 },
  { '\t', 407 },
  { ' ', 407 },
  { ':', -46 },
  { '=', -46 },
  { 'A', 417 },
  { 'L', 418 },
  { '\t', 410 },
  { ' ', 410 },
  { ':', -42 },
  { '=', -42 },
  { 'U', 419 },
  { '\t', 412 },
  { '\n', -47 },
  { '\r', -47 },
  { ' ', 412 },
  { 'X', -48 },
  { '\t', 414 },
  { ' ', 414 },
  { ':', -49 },
  { '=', -49 },
  { 'H', 420 },
  { '\t', 416 },
  { ' ', 416 },
  { ':', -50 },
  { '=', -50 },
  { 'L', 421 },
  { '\t', 418 },
  { ' ', 418 },
  { ':', -51 },
  { '=', -51 },
  { 'A', 422 },
  { '\t', 420 },
  { '\n', -52 },
  { '\r', -52 },
  { ' ', 420 },
  { '\t', 421 },
  { ' ', 421 },
  { ':', -53 },
  { '=', -53 },
  { 'L', 423 },
  { '\t', 423 },
  { ' ', 423 },
  { ':', -54 },
  { '=', -54 },
};

static const uint16 states[425] = {
  0,
  3,
  4,
  7,
  16,
  18,
  19,
  21,
  22,
  23,
  25,
  26,
  27,
  29,
  30,
  31,
  32,
  34,
  35,
  36,
  37,
  39,
  45,
  46,
  47,
  48,
  49,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  114,
  115,
  116,
  117,
  118,
  119,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  189,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  207,
  208,
  209,
  210,
  211,
  212,
  213,
  214,
  215,
  216,
  217,
  221,
  222,
  226,
  227,
  228,
  229,
  231,
  232,
  233,
  237,
  238,
  239,
  240,
  241,
  242,
  243,
  244,
  245,
  249,
  250,
  251,
  252,
  253,
  254,
  255,
  256,
  257,
  261,
  262,
  263,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  295,
  299,
  300,
  301,
  302,
  303,
  304,
  305,
  307,
  308,
  309,
  315,
  319,
  320,
  321,
  322,
  323,
  324,
  326,
  330,
  331,
  332,
  333,
  334,
  336,
  337,
  338,
  339,
  340,
  344,
  345,
  346,
  347,
  348,
  349,
  350,
  351,
  355,
  356,
  357,
  358,
  362,
  363,
  364,
  365,
  369,
  370,
  375,
  380,
  381,
  382,
  383,
  384,
  389,
  394,
  395,
  396,
  400,
  401,
  402,
  403,
  404,
  405,
  406,
  407,
  408,
  409,
  410,
  415,
  416,
  417,
  418,
  419,
  420,
  423,
  424,
  425,
  426,
  429,
  430,
  431,
  432,
  437,
  441,
  442,
  443,
  444,
  445,
  450,
  455,
  456,
  460,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  468,
  469,
  470,
  475,
  476,
  477,
  479,
  480,
  481,
  482,
  483,
  484,
  485,
  486,
  487,
  488,
  492,
  497,
  498,
  502,
  506,
  507,
  511,
  515,
  519,
  523,
  524,
  525,
  526,
  527,
  529,
  533,
  534,
  535,
  539,
  543,
  544,
  545,
  546,
  550,
  554,
  558,
  559,
  560,
  565,
  566,
  567,
  571,
  575,
  579,
  580,
  581,
  582,
  586,
  587,
  589,
  590,
  591,
  592,
  596,
  597,
  598,
  603,
  607,
  608,
  609,
  610,
  611,
  612,
  616,
  617,
  618,
  619,
  623,
  627,
  628,
  632,
  633,
  637,
  638,
  639,
  644,
  645,
  649,
  653,
  656,
  660,
  661,
  662,
  663,
  667,
  668,
  669,
  673,
  674,
  678,
  679,
  683,
  684,
  688,
  689,
  693,
  694,
  698,
  702,
  703,
  707,
};

static uint16 matchLiteral(ptr s, ptr e, Task task)
{ s=s; e=e; task=task; return 0; }

ptr DeviceTestServiceParser_parseData(ptr s, ptr e, Task task)
{
  ptr p;

#ifdef DISPLAY_AT_CMDS
  {
    ptr c = s;
    printf("\nreceived: ");
    while (c != e)
    {
      uint8 ch = *c;
      if (ch == (uint8)13)         printf("\\r");
      else if (ch == (uint8)10)    printf("\\n\n");
      else                         printf("%c",ch);

      c++;
    }
    /* On the target a LF causes output to be printed */
    if (*(c-1) != (uint8)10)
    {
      printf("\n");
    }
  }
#endif

#ifdef TEST_HARNESS
  task = task;
#endif
  for(; (p = findEndOfPacket(s, e)) != 0; s = p)
  {
    if(p == s+1)
    {
      /* Silently discard one character; no packets are that short */
      continue;
    }
    else if(matchLiteral(s, p, task))
    {
      continue;
    }
    else
    {
      union {
        struct DeviceTestServiceCommand_HandleLed DeviceTestServiceCommand_HandleLed;
        struct DeviceTestServiceCommand_HandleAuthResp DeviceTestServiceCommand_HandleAuthResp;
        struct DeviceTestServiceCommand_HandlePskeyGet DeviceTestServiceCommand_HandlePskeyGet;
        struct DeviceTestServiceCommand_HandlePskeySet DeviceTestServiceCommand_HandlePskeySet;
        struct DeviceTestServiceCommand_HandleAncEnable DeviceTestServiceCommand_HandleAncEnable;
        struct DeviceTestServiceCommand_HandleDevCfgUpdate DeviceTestServiceCommand_HandleDevCfgUpdate;
        struct DeviceTestServiceCommand_HandleTouchSensor DeviceTestServiceCommand_HandleTouchSensor;
        struct DeviceTestServiceCommand_HandlePskeyClear DeviceTestServiceCommand_HandlePskeyClear;
        struct DeviceTestServiceCommand_HandleMibPskeyGet DeviceTestServiceCommand_HandleMibPskeyGet;
        struct DeviceTestServiceCommand_HandleAncGetPsKey DeviceTestServiceCommand_HandleAncGetPsKey;
        struct DeviceTestServiceCommand_HandleAncSetPsKey DeviceTestServiceCommand_HandleAncSetPsKey;
        struct DeviceTestServiceCommand_HandleAudioPlayTone DeviceTestServiceCommand_HandleAudioPlayTone;
        struct DeviceTestServiceCommand_HandleDevCfgUpdatePart DeviceTestServiceCommand_HandleDevCfgUpdatePart;
        struct DeviceTestServiceCommand_HandleDtsEndTesting DeviceTestServiceCommand_HandleDtsEndTesting;
        struct DeviceTestServiceCommand_HandleAudioLoopbackStart DeviceTestServiceCommand_HandleAudioLoopbackStart;
        struct DeviceTestServiceCommand_HandleRfTestCarrier DeviceTestServiceCommand_HandleRfTestCarrier;
        struct DeviceTestServiceCommand_HandlePioOutput DeviceTestServiceCommand_HandlePioOutput;
        struct DeviceTestServiceCommand_HandleProximitySensor DeviceTestServiceCommand_HandleProximitySensor;
        struct DeviceTestServiceCommand_HandleAncSetFineGain DeviceTestServiceCommand_HandleAncSetFineGain;
        struct DeviceTestServiceCommand_HandleDevCfgReadPart DeviceTestServiceCommand_HandleDevCfgReadPart;
        struct DeviceTestServiceCommand_HandleDtsSetTestMode DeviceTestServiceCommand_HandleDtsSetTestMode;
        struct DeviceTestServiceCommand_HandleRfTestCfgPower DeviceTestServiceCommand_HandleRfTestCfgPower;
        struct DeviceTestServiceCommand_HandleHallEffectSensor DeviceTestServiceCommand_HandleHallEffectSensor;
        struct DeviceTestServiceCommand_HandleAncReadFineGain DeviceTestServiceCommand_HandleAncReadFineGain;
        struct DeviceTestServiceCommand_HandleRfTestLeRxStart DeviceTestServiceCommand_HandleRfTestLeRxStart;
        struct DeviceTestServiceCommand_HandleRfTestLeTxStart DeviceTestServiceCommand_HandleRfTestLeTxStart;
        struct DeviceTestServiceCommand_HandlePioInput DeviceTestServiceCommand_HandlePioInput;
        struct DeviceTestServiceCommand_HandleAncWriteFineGain DeviceTestServiceCommand_HandleAncWriteFineGain;
        struct DeviceTestServiceCommand_HandleRfTestCfgAddress DeviceTestServiceCommand_HandleRfTestCfgAddress;
        struct DeviceTestServiceCommand_HandleRfTestCfgChannel DeviceTestServiceCommand_HandleRfTestCfgChannel;
        struct DeviceTestServiceCommand_HandleRfTestCfgStopPio DeviceTestServiceCommand_HandleRfTestCfgStopPio;
        struct DeviceTestServiceCommand_HandleAncReadCoarseGain DeviceTestServiceCommand_HandleAncReadCoarseGain;
        struct DeviceTestServiceCommand_HandleRfTestCfgPacket DeviceTestServiceCommand_HandleRfTestCfgPacket;
        struct DeviceTestServiceCommand_HandleRfTestCfgStopTime DeviceTestServiceCommand_HandleRfTestCfgStopTime;
        struct DeviceTestServiceCommand_HandleAccelerometer DeviceTestServiceCommand_HandleAccelerometer;
        struct DeviceTestServiceCommand_HandleAncSetFineGainDual DeviceTestServiceCommand_HandleAncSetFineGainDual;
        struct DeviceTestServiceCommand_HandleAncReadFineGainDual DeviceTestServiceCommand_HandleAncReadFineGainDual;
        struct DeviceTestServiceCommand_HandleAncWriteFineGainDual DeviceTestServiceCommand_HandleAncWriteFineGainDual;
      } u, *uu = &u;
      int state = 0;
      ptr t = s;
      while(t != e && state >= 0)
      {
        char m = my_toupper((char) *t);
        const Arc *a = &arcs[states[state]];
        const Arc *const last_a = &arcs[states[state+1]];
#ifndef TEST_HARNESS
        a = (const Arc *) (void *) UtilFind(0xFFFF, (uint16) m, (const uint16 *) (void *) &a[0].c, 0, sizeof(Arc), (uint16) (last_a - a));
#endif
#ifdef TEST_HARNESS
        while(a != last_a && a->c != m) a++;
#endif
        /*lint -e{801} suppress goto is deprecated */
        if(!a) goto unrecognised;
        state = a->to;
        ++t;
      }
      switch(-state)
      {
        case 1:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleLed.ledValue), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleLed(task, &uu->DeviceTestServiceCommand_HandleLed);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleLed");
            printf(" ledValue=%d", uu->DeviceTestServiceCommand_HandleLed.ledValue);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 2:
          if(match1(skip1(getClassPlus(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAuthResp.response, hexdigit), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAuthResp(task, &uu->DeviceTestServiceCommand_HandleAuthResp);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAuthResp");
            printString("response", &uu->DeviceTestServiceCommand_HandleAuthResp.response);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 3:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePskeyGet.pskey), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePskeyGet(task, &uu->DeviceTestServiceCommand_HandlePskeyGet);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePskeyGet");
            printf(" pskey=%d", uu->DeviceTestServiceCommand_HandlePskeyGet.pskey);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 4:
          if(match1(skip1(getWildString(skip1(skipOnce1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePskeySet.pskey), e), e), e, &uu->DeviceTestServiceCommand_HandlePskeySet.value), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePskeySet(task, &uu->DeviceTestServiceCommand_HandlePskeySet);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePskeySet");
            printf(" pskey=%d", uu->DeviceTestServiceCommand_HandlePskeySet.pskey);
            printString("value", &uu->DeviceTestServiceCommand_HandlePskeySet.value);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 5:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRssiRead(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRssiRead");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 6:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncEnable.mode), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncEnable(task, &uu->DeviceTestServiceCommand_HandleAncEnable);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncEnable");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncEnable.mode);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 7:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAuthStart(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAuthStart");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 8:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleDevCfgUpdate.size), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDevCfgUpdate(task, &uu->DeviceTestServiceCommand_HandleDevCfgUpdate);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDevCfgUpdate");
            printf(" size=%d", uu->DeviceTestServiceCommand_HandleDevCfgUpdate.size);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 9:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleTouchSensor.durationS), e), e), e), e, &uu->DeviceTestServiceCommand_HandleTouchSensor.stopAfter), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleTouchSensor(task, &uu->DeviceTestServiceCommand_HandleTouchSensor);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleTouchSensor");
            printf(" durationS=%d", uu->DeviceTestServiceCommand_HandleTouchSensor.durationS);
            printf(" stopAfter=%d", uu->DeviceTestServiceCommand_HandleTouchSensor.stopAfter);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 10:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncDisable(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncDisable");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 11:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDevCfgRead(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDevCfgRead");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 12:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePskeyClear.pskey), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePskeyClear(task, &uu->DeviceTestServiceCommand_HandlePskeyClear);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePskeyClear");
            printf(" pskey=%d", uu->DeviceTestServiceCommand_HandlePskeyClear.pskey);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 13:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestStop(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestStop");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 14:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAuthDisable(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAuthDisable");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 15:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDtsTestModeQuery(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDtsTestModeQuery");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 16:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleLocalBdaddr(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleLocalBdaddr");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 17:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleMibPskeyGet.pskey), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleMibPskeyGet(task, &uu->DeviceTestServiceCommand_HandleMibPskeyGet);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleMibPskeyGet");
            printf(" pskey=%d", uu->DeviceTestServiceCommand_HandleMibPskeyGet.pskey);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 18:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleTemperature(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleTemperature");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 19:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleBatteryLevel(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleBatteryLevel");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 20:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAudioLoopbackStop(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAudioLoopbackStop");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 21:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(getClassPlus(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncGetPsKey.pskey, hexdigit), e), e), e, &uu->DeviceTestServiceCommand_HandleAncGetPsKey.instance), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncGetPsKey(task, &uu->DeviceTestServiceCommand_HandleAncGetPsKey);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncGetPsKey");
            printString("pskey", &uu->DeviceTestServiceCommand_HandleAncGetPsKey.pskey);
            printf(" instance=%d", uu->DeviceTestServiceCommand_HandleAncGetPsKey.instance);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 22:
          if(match1(skip1(getWildString(skip1(skipOnce1(UtilGetNumber(skip1(skipOnce1(getClassPlus(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncSetPsKey.pskey, hexdigit), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetPsKey.instance), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetPsKey.value), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncSetPsKey(task, &uu->DeviceTestServiceCommand_HandleAncSetPsKey);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncSetPsKey");
            printString("pskey", &uu->DeviceTestServiceCommand_HandleAncSetPsKey.pskey);
            printf(" instance=%d", uu->DeviceTestServiceCommand_HandleAncSetPsKey.instance);
            printString("value", &uu->DeviceTestServiceCommand_HandleAncSetPsKey.value);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 23:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAudioPlayTone.tone), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAudioPlayTone.speakerSelection), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAudioPlayTone.durationMs), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAudioPlayTone(task, &uu->DeviceTestServiceCommand_HandleAudioPlayTone);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAudioPlayTone");
            printf(" tone=%d", uu->DeviceTestServiceCommand_HandleAudioPlayTone.tone);
            printf(" speakerSelection=%d", uu->DeviceTestServiceCommand_HandleAudioPlayTone.speakerSelection);
            printf(" durationMs=%d", uu->DeviceTestServiceCommand_HandleAudioPlayTone.durationMs);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 24:
          if(match1(skip1(getWildString(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleDevCfgUpdatePart.value), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDevCfgUpdatePart(task, &uu->DeviceTestServiceCommand_HandleDevCfgUpdatePart);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDevCfgUpdatePart");
            printString("value", &uu->DeviceTestServiceCommand_HandleDevCfgUpdatePart.value);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 25:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleDtsEndTesting.reboot), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDtsEndTesting(task, &uu->DeviceTestServiceCommand_HandleDtsEndTesting);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDtsEndTesting");
            printf(" reboot=%d", uu->DeviceTestServiceCommand_HandleDtsEndTesting.reboot);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 26:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.micSelection), e), e), e, &uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.speakerSelection), e), e), e, &uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.sampleRate), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAudioLoopbackStart(task, &uu->DeviceTestServiceCommand_HandleAudioLoopbackStart);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAudioLoopbackStart");
            printf(" micSelection=%d", uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.micSelection);
            printf(" speakerSelection=%d", uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.speakerSelection);
            printf(" sampleRate=%d", uu->DeviceTestServiceCommand_HandleAudioLoopbackStart.sampleRate);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 27:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCarrier.channel), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCarrier(task, &uu->DeviceTestServiceCommand_HandleRfTestCarrier);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCarrier");
            printf(" channel=%d", uu->DeviceTestServiceCommand_HandleRfTestCarrier.channel);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 28:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDeviceUnderTestMode(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDeviceUnderTestMode");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 29:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestTxStart(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestTxStart");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 30:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePioAllInputs(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePioAllInputs");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 31:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePioOutput.pio), e), e), e, &uu->DeviceTestServiceCommand_HandlePioOutput.onOff), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePioOutput(task, &uu->DeviceTestServiceCommand_HandlePioOutput);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePioOutput");
            printf(" pio=%d", uu->DeviceTestServiceCommand_HandlePioOutput.pio);
            printf(" onOff=%d", uu->DeviceTestServiceCommand_HandlePioOutput.onOff);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 32:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleProximitySensor.durationS), e), e), e), e, &uu->DeviceTestServiceCommand_HandleProximitySensor.stopAfter), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleProximitySensor(task, &uu->DeviceTestServiceCommand_HandleProximitySensor);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleProximitySensor");
            printf(" durationS=%d", uu->DeviceTestServiceCommand_HandleProximitySensor.durationS);
            printf(" stopAfter=%d", uu->DeviceTestServiceCommand_HandleProximitySensor.stopAfter);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 33:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGain.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGain.gainpath), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGain.gainvalue), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncSetFineGain(task, &uu->DeviceTestServiceCommand_HandleAncSetFineGain);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncSetFineGain");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGain.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGain.gainpath);
            printf(" gainvalue=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGain.gainvalue);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 34:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleDevCfgReadPart.size), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDevCfgReadPart(task, &uu->DeviceTestServiceCommand_HandleDevCfgReadPart);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDevCfgReadPart");
            printf(" size=%d", uu->DeviceTestServiceCommand_HandleDevCfgReadPart.size);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 35:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleDtsSetTestMode.testmode), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleDtsSetTestMode(task, &uu->DeviceTestServiceCommand_HandleDtsSetTestMode);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleDtsSetTestMode");
            printf(" testmode=%d", uu->DeviceTestServiceCommand_HandleDtsSetTestMode.testmode);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 36:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgPower.powerSetting), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgPower(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgPower);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgPower");
            printf(" powerSetting=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgPower.powerSetting);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 37:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleHallEffectSensor.durationS), e), e), e), e, &uu->DeviceTestServiceCommand_HandleHallEffectSensor.stopAfter), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleHallEffectSensor(task, &uu->DeviceTestServiceCommand_HandleHallEffectSensor);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleHallEffectSensor");
            printf(" durationS=%d", uu->DeviceTestServiceCommand_HandleHallEffectSensor.durationS);
            printf(" stopAfter=%d", uu->DeviceTestServiceCommand_HandleHallEffectSensor.stopAfter);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 38:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncReadFineGain.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncReadFineGain.gainpath), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncReadFineGain(task, &uu->DeviceTestServiceCommand_HandleAncReadFineGain);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncReadFineGain");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncReadFineGain.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncReadFineGain.gainpath);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 39:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestLeRxStart.lechannel), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestLeRxStart(task, &uu->DeviceTestServiceCommand_HandleRfTestLeRxStart);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestLeRxStart");
            printf(" lechannel=%d", uu->DeviceTestServiceCommand_HandleRfTestLeRxStart.lechannel);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 40:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(skipOnce1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.lechannel), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.lelength), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.pattern), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestLeTxStart(task, &uu->DeviceTestServiceCommand_HandleRfTestLeTxStart);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestLeTxStart");
            printf(" lechannel=%d", uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.lechannel);
            printf(" lelength=%d", uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.lelength);
            printf(" pattern=%d", uu->DeviceTestServiceCommand_HandleRfTestLeTxStart.pattern);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 41:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandlePioInput.pio), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandlePioInput(task, &uu->DeviceTestServiceCommand_HandlePioInput);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandlePioInput");
            printf(" pio=%d", uu->DeviceTestServiceCommand_HandlePioInput.pio);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 42:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGain.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGain.gainpath), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGain.gainvalue), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncWriteFineGain(task, &uu->DeviceTestServiceCommand_HandleAncWriteFineGain);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncWriteFineGain");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGain.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGain.gainpath);
            printf(" gainvalue=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGain.gainvalue);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 43:
          if(match1(skip1(getClassPlus(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgAddress.logicalAddr), e), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgAddress.bdaddr, hexdigit), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgAddress(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgAddress);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgAddress");
            printf(" logicalAddr=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgAddress.logicalAddr);
            printString("bdaddr", &uu->DeviceTestServiceCommand_HandleRfTestCfgAddress.bdaddr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 44:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgChannel.channel), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgChannel(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgChannel);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgChannel");
            printf(" channel=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgChannel.channel);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 45:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopPio.pio), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgStopPio(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopPio);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgStopPio");
            printf(" pio=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgStopPio.pio);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 46:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncReadCoarseGain.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncReadCoarseGain.gainpath), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncReadCoarseGain(task, &uu->DeviceTestServiceCommand_HandleAncReadCoarseGain);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncReadCoarseGain");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncReadCoarseGain.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncReadCoarseGain.gainpath);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 47:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAudioPlayTestTone(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAudioPlayTestTone");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 48:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(getClassPlus(skip1(matchChar(matchChar(skip1(skipOnce1(skip1(getClassPlus(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.payload, hexdigit), e), e), e), e, '0'), e, 'X'), e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.packetType, hexdigit), e), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.length), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgPacket(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgPacket");
            printString("payload", &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.payload);
            printString("packetType", &uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.packetType);
            printf(" length=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgPacket.length);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 49:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime.reboot), e), e), e), e, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime.timeMs), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgStopTime(task, &uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgStopTime");
            printf(" reboot=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime.reboot);
            printf(" timeMs=%d", uu->DeviceTestServiceCommand_HandleRfTestCfgStopTime.timeMs);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 50:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAccelerometer.durationS), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAccelerometer.stopAfter), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAccelerometer(task, &uu->DeviceTestServiceCommand_HandleAccelerometer);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAccelerometer");
            printf(" durationS=%d", uu->DeviceTestServiceCommand_HandleAccelerometer.durationS);
            printf(" stopAfter=%d", uu->DeviceTestServiceCommand_HandleAccelerometer.stopAfter);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 51:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.gainpath), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.instance0gain), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.instance1gain), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncSetFineGainDual(task, &uu->DeviceTestServiceCommand_HandleAncSetFineGainDual);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncSetFineGainDual");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.gainpath);
            printf(" instance0gain=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.instance0gain);
            printf(" instance1gain=%d", uu->DeviceTestServiceCommand_HandleAncSetFineGainDual.instance1gain);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 52:
          if(t)
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleRfTestCfgStopTouch(task);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleRfTestCfgStopTouch");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 53:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncReadFineGainDual.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncReadFineGainDual.gainpath), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncReadFineGainDual(task, &uu->DeviceTestServiceCommand_HandleAncReadFineGainDual);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncReadFineGainDual");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncReadFineGainDual.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncReadFineGainDual.gainpath);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 54:
          if(match1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(skipOnce1(skip1(UtilGetNumber(skip1(t, e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.mode), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.gainpath), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.instance0gain), e), e), e), e, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.instance1gain), e), e))
          {
#ifndef TEST_HARNESS
            DeviceTestServiceCommand_HandleAncWriteFineGainDual(task, &uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual);
#endif
#ifdef TEST_HARNESS
            printf("Called DeviceTestServiceCommand_HandleAncWriteFineGainDual");
            printf(" mode=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.mode);
            printf(" gainpath=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.gainpath);
            printf(" instance0gain=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.instance0gain);
            printf(" instance1gain=%d", uu->DeviceTestServiceCommand_HandleAncWriteFineGainDual.instance1gain);
            putchar('\n');
#endif
            continue;
          }
          break;
        default:
          break;
      }
      /*
        The message does not contain a recognised AT command or response.
        Pass the data on to the application to have a go at 
      */
unrecognised:
#ifndef TEST_HARNESS
      DeviceTestServiceParser_handleUnrecognised(s, (uint16) (p-s), task);
#endif
#ifdef TEST_HARNESS
      printf("Called handleUnrecognised\n");
#endif
    }
  }

  return s;
}

/*
DeviceTestServiceCommand_HandleAuthStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar T
   MatchChar H
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAuthResp
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar T
   MatchChar H
   MatchChar R
   MatchChar E
   MatchChar S
   MatchChar P
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetClassPlus response
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAuthDisable
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar T
   MatchChar H
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar A
   MatchChar B
   MatchChar L
   MatchChar E
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDtsEndTesting
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar T
   MatchChar S
   MatchChar E
   MatchChar N
   MatchChar D
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar I
   MatchChar N
   MatchChar G
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber reboot
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDtsSetTestMode
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar T
   MatchChar S
   MatchChar S
   MatchChar E
   MatchChar T
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar M
   MatchChar O
   MatchChar D
   MatchChar E
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber testmode
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDtsTestModeQuery
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar T
   MatchChar S
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar M
   MatchChar O
   MatchChar D
   MatchChar E
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncEnable
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar E
   MatchChar N
   MatchChar A
   MatchChar B
   MatchChar L
   MatchChar E
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncDisable
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar A
   MatchChar B
   MatchChar L
   MatchChar E
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncReadFineGain
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar R
   MatchChar E
   MatchChar A
   MatchChar D
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncSetFineGain
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar S
   MatchChar E
   MatchChar T
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainvalue
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncWriteFineGain
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar W
   MatchChar R
   MatchChar I
   MatchChar T
   MatchChar E
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainvalue
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncReadCoarseGain
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar R
   MatchChar E
   MatchChar A
   MatchChar D
   MatchChar C
   MatchChar O
   MatchChar A
   MatchChar R
   MatchChar S
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncReadFineGainDual
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar R
   MatchChar E
   MatchChar A
   MatchChar D
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   MatchChar D
   MatchChar U
   MatchChar A
   MatchChar L
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncSetFineGainDual
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar S
   MatchChar E
   MatchChar T
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   MatchChar D
   MatchChar U
   MatchChar A
   MatchChar L
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance0gain
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance1gain
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncWriteFineGainDual
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar W
   MatchChar R
   MatchChar I
   MatchChar T
   MatchChar E
   MatchChar F
   MatchChar I
   MatchChar N
   MatchChar E
   MatchChar G
   MatchChar A
   MatchChar I
   MatchChar N
   MatchChar D
   MatchChar U
   MatchChar A
   MatchChar L
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber mode
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber gainpath
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance0gain
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance1gain
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncSetPsKey
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar S
   MatchChar E
   MatchChar T
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   Skip " \t"
   Match "=:"
   Skip " \t"
   MatchChar 0
   MatchChar X
   Skip " \t"
   GetClassPlus pskey
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance
   SkipOnce ",;"
   Skip " \t"
   GetWildString value
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAncGetPsKey
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar N
   MatchChar C
   MatchChar G
   MatchChar E
   MatchChar T
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   Skip " \t"
   Match "=:"
   Skip " \t"
   MatchChar 0
   MatchChar X
   Skip " \t"
   GetClassPlus pskey
   SkipOnce ",;"
   Skip " \t"
   GetNumber instance
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleLocalBdaddr
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar L
   MatchChar O
   MatchChar C
   MatchChar A
   MatchChar L
   MatchChar B
   MatchChar D
   MatchChar A
   MatchChar D
   MatchChar D
   MatchChar R
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAudioLoopbackStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar L
   MatchChar O
   MatchChar O
   MatchChar P
   MatchChar B
   MatchChar A
   MatchChar C
   MatchChar K
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber micSelection
   SkipOnce ",;"
   Skip " \t"
   GetNumber speakerSelection
   SkipOnce ",;"
   Skip " \t"
   GetNumber sampleRate
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAudioLoopbackStop
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar L
   MatchChar O
   MatchChar O
   MatchChar P
   MatchChar B
   MatchChar A
   MatchChar C
   MatchChar K
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAudioPlayTestTone
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar D
   MatchChar I
   MatchChar O
   MatchChar P
   MatchChar L
   MatchChar A
   MatchChar Y
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar T
   MatchChar O
   MatchChar N
   MatchChar E
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAudioPlayTone
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar U
   MatchChar D
   MatchChar I
   MatchChar O
   MatchChar P
   MatchChar L
   MatchChar A
   MatchChar Y
   MatchChar T
   MatchChar O
   MatchChar N
   MatchChar E
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber tone
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber speakerSelection
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber durationMs
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestStop
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCarrier
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar A
   MatchChar R
   MatchChar R
   MatchChar I
   MatchChar E
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber channel
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestTxStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar T
   MatchChar X
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgChannel
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar C
   MatchChar H
   MatchChar A
   MatchChar N
   MatchChar N
   MatchChar E
   MatchChar L
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber channel
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgPacket
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar P
   MatchChar A
   MatchChar C
   MatchChar K
   MatchChar E
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   MatchChar 0
   MatchChar X
   Skip " \t"
   GetClassPlus payload
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   MatchChar 0
   MatchChar X
   Skip " \t"
   GetClassPlus packetType
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber length
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgAddress
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar A
   MatchChar D
   MatchChar D
   MatchChar R
   MatchChar E
   MatchChar S
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber logicalAddr
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetClassPlus bdaddr
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgPower
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar P
   MatchChar O
   MatchChar W
   MatchChar E
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber powerSetting
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgStopTime
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   MatchChar T
   MatchChar I
   MatchChar M
   MatchChar E
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber reboot
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber timeMs
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgStopPio
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   MatchChar P
   MatchChar I
   MatchChar O
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pio
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestCfgStopTouch
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   MatchChar T
   MatchChar O
   MatchChar U
   MatchChar C
   MatchChar H
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDeviceUnderTestMode
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar D
   MatchChar U
   MatchChar T
   MatchChar M
   MatchChar O
   MatchChar D
   MatchChar E
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestLeTxStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar L
   MatchChar E
   MatchChar T
   MatchChar X
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber lechannel
   SkipOnce ",;"
   Skip " \t"
   GetNumber lelength
   SkipOnce ",;"
   Skip " \t"
   GetNumber pattern
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRfTestLeRxStart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar F
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar L
   MatchChar E
   MatchChar R
   MatchChar X
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber lechannel
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePioOutput
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar P
   MatchChar I
   MatchChar O
   MatchChar O
   MatchChar U
   MatchChar T
   MatchChar P
   MatchChar U
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pio
   SkipOnce ",;"
   Skip " \t"
   GetNumber onOff
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePioInput
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar P
   MatchChar I
   MatchChar O
   MatchChar I
   MatchChar N
   MatchChar P
   MatchChar U
   MatchChar T
   MatchChar P
   MatchChar I
   MatchChar O
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pio
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePioAllInputs
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar P
   MatchChar I
   MatchChar O
   MatchChar I
   MatchChar N
   MatchChar P
   MatchChar U
   MatchChar T
   MatchChar S
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleLed
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar L
   MatchChar E
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber ledValue
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleRssiRead
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar S
   MatchChar S
   MatchChar I
   MatchChar R
   MatchChar E
   MatchChar A
   MatchChar D
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePskeySet
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   MatchChar S
   MatchChar E
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pskey
   SkipOnce ",;"
   Skip " \t"
   GetWildString value
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePskeyGet
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   MatchChar G
   MatchChar E
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pskey
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandlePskeyClear
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   MatchChar C
   MatchChar L
   MatchChar E
   MatchChar A
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pskey
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleMibPskeyGet
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar P
   MatchChar S
   MatchChar K
   MatchChar E
   MatchChar Y
   MatchChar M
   MatchChar I
   MatchChar B
   MatchChar G
   MatchChar E
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber pskey
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleAccelerometer
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar A
   MatchChar C
   MatchChar C
   MatchChar E
   MatchChar L
   MatchChar E
   MatchChar R
   MatchChar O
   MatchChar M
   MatchChar E
   MatchChar T
   MatchChar E
   MatchChar R
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber durationS
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber stopAfter
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleProximitySensor
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar P
   MatchChar R
   MatchChar O
   MatchChar X
   MatchChar I
   MatchChar M
   MatchChar I
   MatchChar T
   MatchChar Y
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber durationS
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber stopAfter
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleTouchSensor
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar T
   MatchChar O
   MatchChar U
   MatchChar C
   MatchChar H
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber durationS
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber stopAfter
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleHallEffectSensor
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar S
   MatchChar T
   MatchChar H
   MatchChar A
   MatchChar L
   MatchChar L
   MatchChar E
   MatchChar F
   MatchChar F
   MatchChar E
   MatchChar C
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber durationS
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetNumber stopAfter
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleTemperature
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar T
   MatchChar E
   MatchChar M
   MatchChar P
   MatchChar E
   MatchChar R
   MatchChar A
   MatchChar T
   MatchChar U
   MatchChar R
   MatchChar E
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleBatteryLevel
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar B
   MatchChar A
   MatchChar T
   MatchChar T
   MatchChar E
   MatchChar R
   MatchChar Y
   MatchChar L
   MatchChar E
   MatchChar V
   MatchChar E
   MatchChar L
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDevCfgRead
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar E
   MatchChar V
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar R
   MatchChar E
   MatchChar A
   MatchChar D
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDevCfgReadPart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar E
   MatchChar V
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar R
   MatchChar E
   MatchChar A
   MatchChar D
   MatchChar P
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber size
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDevCfgUpdate
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar E
   MatchChar V
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar U
   MatchChar P
   MatchChar D
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber size
   Skip " \t"
   Match "\r\n"


DeviceTestServiceCommand_HandleDevCfgUpdatePart
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar D
   MatchChar E
   MatchChar V
   MatchChar C
   MatchChar F
   MatchChar G
   MatchChar U
   MatchChar P
   MatchChar D
   MatchChar P
   MatchChar A
   MatchChar R
   MatchChar T
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetWildString value
   Skip " \t"
   Match "\r\n"


*/
