/*!
    \copyright Copyright (c) 2022 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version %%version
    \file 
    \brief The bt_device_handover marshal type declarations. This file is generated by D:/Work/Qcc/qcc514x-qcc304x-src_headset-ADK-22.2-CS1-r00298.1/adk/tools/packages/typegen/typegen.py.
*/

#ifndef _BT_DEVICE_HANDOVER_MARSHAL_TYPEDEF_H__
#define _BT_DEVICE_HANDOVER_MARSHAL_TYPEDEF_H__

#include <csrtypes.h>
#include <csrtypes.h>
#include <marshal_common.h>
#include <bt_device_typedef.h>
#include <domain_marshal_types.h>
#include <app/marshal/marshal_if.h>

extern const marshal_type_descriptor_t marshal_type_descriptor_bt_device_handover_t;
extern const marshal_type_descriptor_t marshal_type_descriptor_bt_device_handover_le_t;

#define BT_DEVICE_HANDOVER_MARSHAL_TYPES_TABLE(ENTRY)\
    ENTRY(bt_device_handover_t)\
    ENTRY(bt_device_handover_le_t)

#endif /* _BT_DEVICE_HANDOVER_MARSHAL_TYPEDEF_H__ */

