/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_cas_server/gatt_cas_server_db.dbi_
 */
#ifndef __GATT_CAS_SERVER_DB_H
#define __GATT_CAS_SERVER_DB_H

#include <csrtypes.h>

#define HANDLE_COMMON_AUDIO_SERVICE     (0x0001)
#define HANDLE_COMMON_AUDIO_SERVICE_END (0xffff)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);
const uint16 *GattGetConstDatabase(uint16 *len);

#endif

/* End-of-File */
